"""empty message

Revision ID: 0fb8a951645f
Revises: 
Create Date: 2021-09-27 19:33:43.386944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb8a951645f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('customer_source', sa.Integer(), nullable=False),
    sa.Column('customer_target', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('customer_source_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('customer_target_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_source'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['customer_target'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('customer')
    # ### end Alembic commands ###
